name: CI Pipeline

on:
  push:
    branches:
      - master
      - feature/thirdbranch
  pull_request:

  workflow_dispatch:
   inputs:
          name:
            description: 'Your name'
            required: true
            default: 'World'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -la
          find . -type f

      - name: Show secondfile contents
        run: cat secondfile.txt  

      - name: Show Python file
        run: cat third-mandate.py

      - name: Run tests
        run: |
          echo "Add your build/test commands here"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Add your deployment commands here"       
   
          environment:
      - name: Approvals
        run: echo "Deployment approved"

      - name: Show Login ID
        run: echo "${{ secrets.LOGIN_ID }}"      

      - name: Login
        run: |
          USERNAME="${{ secrets.LOGIN_ID }}"
          PASSWORD="${{ secrets.LOGIN_PASSWORD }}"

          echo "Login process started"